import { 
    History, 
    Location 
} from 'history';

import { 
    match 
} from 'react-router';

import * as GeneralTypes from '../../../reducers/generalTypes';

export type PorfolioNavigationProps = {
    archive: GeneralTypes.ArchiveObj,
    bigImagesPortfolio: GeneralTypes.PortfoliObj,
    bigSliderPortfolio: GeneralTypes.PortfoliObj,
    galleryPortfolio: GeneralTypes.PortfoliObj,
    smallGalleryPortfolio: GeneralTypes.PortfoliObj,
    smallImagesPortfolio: GeneralTypes.PortfoliObj,
    smallSliderPortfolio: GeneralTypes.PortfoliObj,
    component: string,
    twoColumnsPage: GeneralTypes.ColumnsPageObj,
    threeColumnsPage: GeneralTypes.ColumnsPageObj,
    fourColumnsPage: GeneralTypes.ColumnsPageObj,
    twoColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    threeColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    fourColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    fiveColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    overlayPage: GeneralTypes.ColumnsWidePageObj,
    overlayWithInfoPage: GeneralTypes.ColumnsWidePageObj,
    simpleOverlayPage: GeneralTypes.ColumnsWidePageObj,
    slideFromImageLeftPage: GeneralTypes.ColumnsWidePageObj,
    switchImagePage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsCoordinateRange>,
    standardPage: GeneralTypes.ColumnsWidePageObj,
    galleryPage: GeneralTypes.ColumnsWidePageObj,
    galleryWithSpacePage: GeneralTypes.ColumnsWidePageObj,
    stoneWallPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    stoneWallWidePage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    metroPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    pinterest3ColumnsPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    portfolioGalleryPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsCoordinateRange>,
    unmountComp: GeneralTypes.UnmountComponent,
    staticContext: undefined
    history: History,
    location: Location,
    match: match,
    addMoreItemsStylesStateForFourColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    addMoreItemsStylesStateForThreeColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    addMoreItemsStylesStateForTwoColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    fetchArchive: (category: string, step: number) => void,
    fetchArchiveSuccess: (array: Array<GeneralTypes.ArchiveItem>) => {array: Array<GeneralTypes.ArchiveItem>},
    fetchFiveColumnsWidePage: () => void,
    fetchFiveColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchFourColumnsPage: (step: number, category: string, screenWidth: number, numOfItemsInArray: number, itemsStyleValuesObj: Array<GeneralTypes.ItemsStyleValuesObj>) => void,
    fetchFourColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchFourColumnsWidePage: () => void,
    fetchFourColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchGalleryPage: () => void,
    fetchGalleryPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchGalleryWithSpacePage: () => void,
    fetchGalleryWithSpacePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchMetroPage: () => void,
    fetchMetroPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchOverlayPage: () => void,
    fetchOverlayPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchOverlayWithInfoPage: () => void,
    fetchOverlayWithInfoPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchPinterest3ColumnsPage: () => void,
    fetchPinterest3ColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchPortfolioGalleryPage: () => void,
    fetchPortfolioGalleryPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchSimpleOverlayPage: () => void,
    fetchSimpleOverlayPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchSlideFromImageLeftPage: () => void,
    fetchSlideFromImageLeftPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchStandardPage: () => void,
    fetchStandardPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchStoneWallPage: () => void,
    fetchStoneWallPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchStoneWallWidePage: () => void,
    fetchStoneWallWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchSwitchImagePage: () => void,
    fetchSwitchImagePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchThreeColumnsPage: (step: number, category: string, screenWidth: number, numOfItemsInArray: number, itemsStyleValuesObj: Array<GeneralTypes.ItemsStyleValuesObj>) => void,
    fetchThreeColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchThreeColumnsWidePage: () => void,
    fetchThreeColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchTwoColumnsPage: (step: number, category: string, screenWidth: number, numOfItemsInArray: number, itemsStyleValuesObj: Array<GeneralTypes.ItemsStyleValuesObj>) => void,
    fetchTwoColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchTwoColumnsWidePage: () => void,
    fetchTwoColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForFourColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    initItemsStylesStateForMetroPage: (arr: Array<number>) => {arr: Array<number>},
    initItemsStylesStateForPinterest3ColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    initItemsStylesStateForStoneWallPage: (arr: Array<number>) => {arr: Array<number>},
    initItemsStylesStateForStoneWallWidePage: (arr: Array<number>) => {arr: Array<number>},
    initItemsStylesStateForThreeColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    initItemsStylesStateForTwoColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    loadMoreDisableButtonStateForArchive: (val: boolean) => {val: boolean},
    loadMoreDisableButtonStateForFourColumnsPage: (val: boolean) => {val: boolean},
    loadMoreDisableButtonStateForThreeColumnsPage: (val: boolean) => {val: boolean},
    loadMoreDisableButtonStateForTwoColumnsPage: (val: boolean) => {val: boolean},
    loadMoreFourColumnsPageSuccess: () => {},
    loadMoreThreeColumnsPageSuccess: () => {},
    loadMoreTwoColumnsPageSuccess: () => {},
    portfolioNavigationOnClickStart: (path: string, page: string, category: string) => {path: string, page: string, category: string},
    setArchiveCategory: (category: string) => {category: string},
    setCategoriesFourColumnsPage: (array: Array<GeneralTypes.CategoriesItem>) => {array: Array<GeneralTypes.CategoriesItem>},
    setCategoriesThreeColumnsPage: (array: Array<GeneralTypes.CategoriesItem>) => {array: Array<GeneralTypes.CategoriesItem>},
    setCategoriesTwoColumnsPage: (array: Array<GeneralTypes.CategoriesItem>) => {array: Array<GeneralTypes.CategoriesItem>},
    setHistoryPopFromPortfolioItem: (val: string) => {val: string},
    setTopPositionOfTheItemForFourColumnsPage: (id: string, val: number) => {id: string, val: number},
    setTopPositionOfTheItemForThreeColumnsPage: (id: string, val: number) => {id: string, val: number},
    setTopPositionOfTheItemForTwoColumnsPage: (id: string, val: number) => {id: string, val: number},
    updateItemsStyleValuesFourColumnsPage: (image: string, obj: GeneralTypes.ItemsStyleValuesObj) => {image: string, obj: GeneralTypes.ItemsStyleValuesObj},
    updateItemsStyleValuesThreeColumnsPage: (image: string, obj: GeneralTypes.ItemsStyleValuesObj) => {image: string, obj: GeneralTypes.ItemsStyleValuesObj},
    updateItemsStyleValuesTwoColumnsPage: (image: string, obj: GeneralTypes.ItemsStyleValuesObj) => {image: string, obj: GeneralTypes.ItemsStyleValuesObj}
}

export type MapStateToPropsTypes = {
    portfolioGalleryPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsCoordinateRange>,
    archive: GeneralTypes.ArchiveObj,
    switchImagePage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsCoordinateRange>,
    simpleOverlayPage: GeneralTypes.ColumnsWidePageObj,
    slideFromImageLeftPage: GeneralTypes.ColumnsWidePageObj,
    overlayPage: GeneralTypes.ColumnsWidePageObj,
    overlayWithInfoPage: GeneralTypes.ColumnsWidePageObj,
    standardPage: GeneralTypes.ColumnsWidePageObj,
    galleryPage: GeneralTypes.ColumnsWidePageObj,
    galleryWithSpacePage: GeneralTypes.ColumnsWidePageObj,
    stoneWallPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    stoneWallWidePage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    metroPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    pinterest3ColumnsPage: GeneralTypes.ColumnsWidePageObj & Array<GeneralTypes.ItemsStyleValuesObj> & Array<GeneralTypes.ItemsTopPositionItem>,
    twoColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    threeColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    fourColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    fiveColumnsWidePage: GeneralTypes.ColumnsWidePageObj,
    twoColumnsPage: GeneralTypes.ColumnsPageObj,
    threeColumnsPage: GeneralTypes.ColumnsPageObj,
    fourColumnsPage: GeneralTypes.ColumnsPageObj,
    bigImagesPortfolio: GeneralTypes.PortfoliObj,
    bigSliderPortfolio: GeneralTypes.PortfoliObj,
    galleryPortfolio: GeneralTypes.PortfoliObj,
    smallGalleryPortfolio: GeneralTypes.PortfoliObj,
    smallImagesPortfolio: GeneralTypes.PortfoliObj,
    smallSliderPortfolio: GeneralTypes.PortfoliObj,
    unmountComp: GeneralTypes.UnmountComponent
}

export type MapDispatchToPropsTypes = {
    fetchPortfolioGalleryPage: () => void,
    fetchPortfolioGalleryPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchArchive: (category: string, step: number) => void,
    fetchArchiveSuccess: (array: Array<GeneralTypes.ArchiveItem>) => {array: Array<GeneralTypes.ArchiveItem>},
    setArchiveCategory: (category: string) => {category: string},
    loadMoreDisableButtonStateForArchive: (val: boolean) => {val: boolean},
    fetchSwitchImagePage: () => void,
    fetchSwitchImagePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchSimpleOverlayPage: () => void,
    fetchSimpleOverlayPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchSlideFromImageLeftPage: () => void,
    fetchSlideFromImageLeftPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchOverlayPage: () => void,
    fetchOverlayPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchOverlayWithInfoPage: () => void,
    fetchOverlayWithInfoPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchStandardPage: () => void,
    fetchStandardPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchGalleryPage: () => void,
    fetchGalleryPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchGalleryWithSpacePage: () => void,
    fetchGalleryWithSpacePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchStoneWallPage: () => void,
    fetchStoneWallPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForStoneWallPage: (arr: Array<number>) => {arr: Array<number>},
    fetchStoneWallWidePage: () => void,
    fetchStoneWallWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForStoneWallWidePage: (arr: Array<number>) => {arr: Array<number>},
    fetchMetroPage: () => void,
    fetchMetroPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForMetroPage: (arr: Array<number>) => {arr: Array<number>},
    fetchPinterest3ColumnsPage: () => void,
    fetchPinterest3ColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForPinterest3ColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    fetchTwoColumnsWidePage: () => void,
    fetchTwoColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchThreeColumnsWidePage: () => void,
    fetchThreeColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchFourColumnsWidePage: () => void,
    fetchFourColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchFiveColumnsWidePage: () => void,
    fetchFiveColumnsWidePageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    fetchTwoColumnsPage: (step: number, category: string, screenWidth: number, numOfItemsInArray: number, itemsStyleValuesObj: Array<GeneralTypes.ItemsStyleValuesObj>) => void,
    fetchTwoColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForTwoColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    addMoreItemsStylesStateForTwoColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    setCategoriesTwoColumnsPage: (array: Array<GeneralTypes.CategoriesItem>) => {array: Array<GeneralTypes.CategoriesItem>},
    loadMoreTwoColumnsPageSuccess: () => {},
    loadMoreDisableButtonStateForTwoColumnsPage: (val: boolean) => {val: boolean},
    updateItemsStyleValuesTwoColumnsPage: (image: string, obj: GeneralTypes.ItemsStyleValuesObj) => {image: string, obj: GeneralTypes.ItemsStyleValuesObj},
    setTopPositionOfTheItemForTwoColumnsPage: (id: string, val: number) => {id: string, val: number},
    fetchThreeColumnsPage: (step: number, category: string, screenWidth: number, numOfItemsInArray: number, itemsStyleValuesObj: Array<GeneralTypes.ItemsStyleValuesObj>) => void,
    fetchThreeColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForThreeColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    addMoreItemsStylesStateForThreeColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    setCategoriesThreeColumnsPage: (array: Array<GeneralTypes.CategoriesItem>) => {array: Array<GeneralTypes.CategoriesItem>},
    loadMoreThreeColumnsPageSuccess: () => {},
    loadMoreDisableButtonStateForThreeColumnsPage: (val: boolean) => {val: boolean},
    updateItemsStyleValuesThreeColumnsPage: (image: string, obj: GeneralTypes.ItemsStyleValuesObj) => {image: string, obj: GeneralTypes.ItemsStyleValuesObj},
    setTopPositionOfTheItemForThreeColumnsPage: (id: string, val: number) => {id: string, val: number},
    fetchFourColumnsPage: (step: number, category: string, screenWidth: number, numOfItemsInArray: number, itemsStyleValuesObj: Array<GeneralTypes.ItemsStyleValuesObj>) => void,
    fetchFourColumnsPageSuccess: (array: Array<GeneralTypes.BannerItemObj>) => {array: Array<GeneralTypes.BannerItemObj>},
    initItemsStylesStateForFourColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    addMoreItemsStylesStateForFourColumnsPage: (arr: Array<number>) => {arr: Array<number>},
    setCategoriesFourColumnsPage: (array: Array<GeneralTypes.CategoriesItem>) => {array: Array<GeneralTypes.CategoriesItem>},
    loadMoreFourColumnsPageSuccess: () => {},
    loadMoreDisableButtonStateForFourColumnsPage: (val: boolean) => {val: boolean},
    updateItemsStyleValuesFourColumnsPage: (image: string, obj: GeneralTypes.ItemsStyleValuesObj) => {image: string, obj: GeneralTypes.ItemsStyleValuesObj},
    setTopPositionOfTheItemForFourColumnsPage: (id: string, val: number) => {id: string, val: number},
    setHistoryPopFromPortfolioItem: (val: string) => {val: string},
    portfolioNavigationOnClickStart: (path: string, page: string, category: string) => {path: string, page: string, category: string}
}
